apiVersion: v1
kind: Service
metadata:
  name: frontend-blue
  labels:
    app: frontend
    color: blue
spec:
  selector:
    app: frontend
    color: blue
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-green
  labels:
    app: frontend
    color: green
spec:
  selector:
    app: frontend
    color: green
  ports:
    - port: 80
      targetPort: 80
